/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerProfile = IDL.Record({
  'age' : IDL.Nat,
  'theme' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getClues' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getPlayerStats' : IDL.Func([IDL.Text], [IDL.Nat, IDL.Nat], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [PlayerProfile], ['query']),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerProfile = IDL.Record({
    'age' : IDL.Nat,
    'theme' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getClues' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getPlayerStats' : IDL.Func([IDL.Text], [IDL.Nat, IDL.Nat], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [PlayerProfile], ['query']),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };